import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const googleSans = localFont({
  src: [
    { path: "../../public/font/GoogleSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/font/GoogleSans-Italic.ttf", weight: "400", style: "italic" },
    { path: "../../public/font/GoogleSans-Medium.ttf", weight: "500", style: "normal" },
    { path: "../../public/font/GoogleSans-MediumItalic.ttf", weight: "500", style: "italic" },
    { path: "../../public/font/GoogleSans-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../../public/font/GoogleSans-SemiBoldItalic.ttf", weight: "600", style: "italic" },
    { path: "../../public/font/GoogleSans-Bold.ttf", weight: "700", style: "normal" },
    { path: "../../public/font/GoogleSans-BoldItalic.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-sans",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={googleSans.variable}>
      <body
        className={`${googleSans.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
